name: conradj
favicon: null
layout_spectrum: 0
typography_spectrum: 0.7731440183706582
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#f5fbf9'
    - '#0b0a05'
    - '#bf7400'
    - '#8e4f00'
    - '#e6a500'
  brandStrength: 0.5398857765831053
  lightness: 0.28229147335514426
  saturation: 0.25
  rhythmicContrast: 0.4387758714146912
purpose: []
