name: conradj
favicon: null
layout_spectrum: 1
typography_spectrum: 0.7731440183706582
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#020204'
    - '#f9220e'
    - '#f39b13'
    - '#f96817'
    - '#0202b1'
  brandStrength: 0
  lightness: 0.28229147335514426
  saturation: 0.0625
  rhythmicContrast: 0.75
purpose: []
