name: conradj
favicon: null
layout_spectrum: 0
typography_spectrum: 0.86344
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#020204'
    - '#f9220e'
    - '#f39b13'
    - '#f96817'
    - '#0202b1'
  brandStrength: 0.5
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
